services:
  - type: web
    name: ecojac-api
    runtime: docker
    plan: free
    envVars:
      - key: APP_KEY
        value: "base64:51HZzVcSYyf42odWZT6YqpaY5Y7GgJ+uaZZfn7QgQ7k="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://antigravity-txtk.onrender.com"
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
